# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/
toggle_key: OFF

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":em"
    replace: "—"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%b %d, %Y - %a"

  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"


  # Shell commands
  # be careful because if in terminal, will run result
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo echo"

  - trigger: ":lorem"
    replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum faucibus vitae aliquet nec ullamcorper."

  - trigger: ":yteuler"
    replace: "A screencast series learning Rust by solving Project Euler problems.\n\nFor more Rust, see my notes and examples at: https://mkaz.blog/working-with-rust"

  - trigger: ":tweuler"
    replace: "Just released Euler #6 in Rust, the next in my screencast series learning Rust going through Project Euler problems."

  - trigger: ":wp"
    replace: "WordPress"

  - trigger: ":gb"
    replace: "Gutenberg"

